// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {Groth16Verifier} from "../src/zk/Groth16Verifier.sol";
import {CrownZkReservesGate} from "../src/zk/CrownZkReservesGate.sol";
import {CrownZkCredit} from "../src/zk/CrownZkCredit.sol";

contract MockUsdc {
    mapping(address => uint256) public balanceOf;
    mapping(address => mapping(address => uint256)) public allowance;
    function mint(address to, uint256 amt) external { balanceOf[to] += amt; }
    function approve(address sp, uint256 amt) external returns (bool) { allowance[msg.sender][sp] = amt; return true; }
    function transfer(address to, uint256 amt) external returns (bool) {
        balanceOf[msg.sender] -= amt; balanceOf[to] += amt; return true;
    }
    function transferFrom(address f, address t, uint256 amt) external returns (bool) {
        allowance[f][msg.sender] -= amt; balanceOf[f] -= amt; balanceOf[t] += amt; return true;
    }
}

/// @dev Uses a real Groth16 proof generated by zk/scripts/prove.sh (ok=1, 700k, hot subject).
contract ZkReservesTest is Test {
    address constant HOT = 0x6708e21113922ED588bBCcAA5ef756BEcBb2a7d1;

    Groth16Verifier v;
    CrownZkReservesGate gate;
    CrownZkCredit credit;
    MockUsdc usdc;

    // Filled from proofs/proof_solidity.json after prove — update if zkey regenerates.
    uint256[2] internal a;
    uint256[2][2] internal b;
    uint256[2] internal c;
    uint256[3] internal pub;

    function setUp() public {
        // Load proof vectors from env-free hardcoded sample produced by prove.sh in this repo build.
        // If setup.sh re-runs, refresh these from zk/proofs/proof_solidity.json
        string memory json = vm.readFile("zk/proofs/proof_solidity.json");
        a[0] = vm.parseJsonUint(json, ".a[0]");
        a[1] = vm.parseJsonUint(json, ".a[1]");
        b[0][0] = vm.parseJsonUint(json, ".b[0][0]");
        b[0][1] = vm.parseJsonUint(json, ".b[0][1]");
        b[1][0] = vm.parseJsonUint(json, ".b[1][0]");
        b[1][1] = vm.parseJsonUint(json, ".b[1][1]");
        c[0] = vm.parseJsonUint(json, ".c[0]");
        c[1] = vm.parseJsonUint(json, ".c[1]");
        pub[0] = vm.parseJsonUint(json, ".publicSignals[0]");
        pub[1] = vm.parseJsonUint(json, ".publicSignals[1]");
        pub[2] = vm.parseJsonUint(json, ".publicSignals[2]");

        // Re-prove with ok=1 if last prove was under-threshold
        if (pub[0] != 1) {
            // skip — require ok proof file
        }

        v = new Groth16Verifier();
        gate = new CrownZkReservesGate(address(v), HOT);
        usdc = new MockUsdc();
        credit = new CrownZkCredit(address(usdc), address(gate), HOT, HOT);
    }

    function test_submit_proof_and_borrow() public {
        vm.skip(pub[0] != 1); // need valid ≥700k proof in file

        gate.submitProof(a, b, c, pub);
        assertTrue(gate.isProven(HOT));

        address lp = address(0xBEEF);
        usdc.mint(lp, 500_000e6);
        vm.startPrank(lp);
        usdc.approve(address(credit), 500_000e6);
        credit.supply(500_000e6);
        vm.stopPrank();

        vm.prank(HOT);
        credit.borrow(400_000e6); // under 70% of 700k = 490k
        assertEq(usdc.balanceOf(HOT), 400_000e6);
    }

    function test_verifier_rejects_ok_zero_via_gate() public {
        pub[0] = 0;
        vm.expectRevert(CrownZkReservesGate.BadProof.selector);
        gate.submitProof(a, b, c, pub);
    }
}
